-- ============================================================
-- Project: Semiconductor PVD Process Quality Analysis
-- File   : 01_create_tables.sql
-- Purpose: Create normalized Oracle tables for PVD analysis
-- ============================================================


-- 1. PVD process run master
CREATE TABLE pvd_run (
    run_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    material_type   VARCHAR2(10) NOT NULL,
    source_row_no   NUMBER NOT NULL,

    CONSTRAINT pk_pvd_run
        PRIMARY KEY (run_id),

    CONSTRAINT uq_pvd_run
        UNIQUE (material_type, source_row_no),

    CONSTRAINT ck_pvd_material
        CHECK (material_type IN ('AlCu', 'WTi'))
);


-- 2. Process sensor measurements
CREATE TABLE sensor_measurement (
    run_id          NUMBER NOT NULL,
    sensor_no       NUMBER NOT NULL,
    sensor_value    NUMBER,

    CONSTRAINT pk_sensor_measurement
        PRIMARY KEY (run_id, sensor_no),

    CONSTRAINT fk_sensor_run
        FOREIGN KEY (run_id)
        REFERENCES pvd_run(run_id),

    CONSTRAINT ck_sensor_no
        CHECK (sensor_no BETWEEN 1 AND 108)
);


-- 3. Thickness measurements
CREATE TABLE thickness_measurement (
    run_id              NUMBER NOT NULL,
    measurement_point   NUMBER NOT NULL,
    thickness_value     NUMBER,

    CONSTRAINT pk_thickness_measurement
        PRIMARY KEY (run_id, measurement_point),

    CONSTRAINT fk_thickness_run
        FOREIGN KEY (run_id)
        REFERENCES pvd_run(run_id),

    CONSTRAINT ck_measurement_point
        CHECK (measurement_point BETWEEN 1 AND 17)
);